language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true

# command to prepare the system to install prerequisites or dependencies
before_install:
  # Install Gstreamer
  - ls -l /usr/lib/x86_64-linux-gnu/libm.so
  - sudo add-apt-repository -y ppa:donk/gstreamer
  - sudo apt-get -qq update
  - sudo apt-get install -qq python-gst0.10 gstreamer0.10-plugins-good gstreamer0.10-gnonlin gstreamer0.10-plugins-ugly gstreamer0.10-plugins-bad
  - ls -l /usr/lib/x86_64-linux-gnu/libm.so

  # Install conda
  - sudo pip install conda
  # install deps
  - sudo conda init
  - sudo conda update conda --yes
  - deps="setuptools numpy scipy matplotlib h5py pytables numpydoc sphinx coverage pip"  
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PYTHONPATH=$HOME/py/lib:$PYTHONPATH

  - ls -l /home/travis/py/lib/
  - ls -l /home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/
  - ls -l /usr/lib/python2.7/dist-packages/
  - ls -l /home/travis/py/lib/python2.7/site-packages
  - python -c "import sys; print sys.path"
  # Install TimeSide
  - python setup.py install

# command to run tests
before_script:
  - python tests/get_samples.py
  - pip install coveralls

script:
  - echo $PYTHONPATH 
  - coverage run --source=timeside --omit=timeside/analyzer/aubio/aubio_*.py,timeside/analyzer/yaafe.py,timeside/analyzer/limsi_sad.py,timeside/analyzer/vamp_plugin.py tests/run_all_tests

after_success:
  - coveralls