language: python
python:
  - "2.7"
#virtualenv:
#  system_site_packages: true

# command to prepare the system to install prerequisites or dependencies
before_install:

  # Install Gstreamer
  - sudo add-apt-repository -y ppa:donk/gstreamer
  - sudo apt-get -qq update
  - sudo apt-get install -qq python-gst0.10 gstreamer0.10-plugins-good gstreamer0.10-gnonlin gstreamer0.10-plugins-ugly gstreamer0.10-plugins-bad
  # Instal some Python packages
  #- sudo apt-get install python-setuptools

  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  
  # Install binary dependencies with conda
  - deps="setuptools coverage numpy scipy=0.11.0 matplotlib h5py pytables"  
  # Do not use conda but use conda site-package to get the installed package
  #- export PYTHONPATH=$HOME/py/lib/python2.7/site-packages:$PYTHONPATH
  - conda create -q -n test-environment $deps python=$TRAVIS_PYTHON_VERSION 
  - rm ~/miniconda/envs/test-environment/lib/libm.so.6 # use the system libm; see github.com/ContinuumIO/anaconda-issues/issues/182
  - source activate test-environment

install:
  # Install TimeSide
  - python setup.py install

# command to run tests
before_script:
  - pip install -U coverage
  - pip install coveralls


script:
  - coverage run --source=timeside --omit=timeside/analyzer/aubio/aubio_*.py,timeside/analyzer/yaafe.py,timeside/analyzer/limsi_sad.py,timeside/analyzer/vamp_plugin.py tests/run_all_tests
  - ls -l /home/travis/build/yomguy/TimeSide/tests/samples/

after_success:
  - coveralls
